---
spec_version: 1
kind: blueprint
#
metadata:
  description: 
    Nothing
clouds:
  - AWS: us-west-2
applications:
  - sample-application:  
      instances: 1          
services:
  - sample-application-terraform:
      input_values:
      - role_arn: PowerUserAccess
      - sandbox_id: $colony.environment.id      
debugging:
  availability: enabled-on
